name: Pull Request Title Validation

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate_title:
    runs-on: ubuntu-latest

    steps:
      - name: Check Pull Request Title
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "Pull Request Title: $title"

          if [[ $title =~ ^\[MAINTENANCE\].* ]] || [[ $title =~ ^[0-9]{16} ]]; then
            echo "Valid title."
          else
            echo "Invalid pull request title. The title should either start with '[MAINTENANCE]' or be a 16-digit number."
            exit 1
          fi
      - name: Add deploy URL to PR description
        uses: chabroA/action-append-pr-description@master
        with:
          auth: ${{ github.token }}
          repo: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}
          pr: ${{ github.event.number }}
          url: "https://my-url.test"
          message: "My url :" 
