name: Pull Request Title Validation

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate_title:
    runs-on: ubuntu-latest

    steps:
      - name: Check Pull Request Title
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "Pull Request Title: $title"

          if [[ $title =~ ^\[MAINTENANCE\].* ]] || [[ $title =~ ^[0-9]{16} ]]; then
            echo "Valid title."
          else
            echo "Invalid pull request title. The title should either start with '[MAINTENANCE]' or be a 16-digit number."
            exit 1
          fi
      - name: Add link to PR description
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ github.token }}
        run: |
          title="${{ github.event.pull_request.title }}"
          description="${{ github.event.pull_request.body }}"
          if [[ $title =~ ^[0-9]{16} ]]; then
            pr_number=$(echo $title | cut -c1-16)
            link="www.example.com/$pr_number"
            if ! echo "$description" | grep -q "$link"; then
              gh api \
                --method PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/$GITHUB_REPO/pulls/$GITHUB_NUMBER/comments \
                -f "body=This PR is related to $link"
            fi
          fi
